### ISSUE TITLE
Could you provide more details on how to obtain Light-R1-32B (merged model)?

### ISSUE THREAD

**Issue by zjuruizhechen** [Qihoo360/Light-R1#21]
As titled. Thanks a lot for your response.

**Comment by HqWei** [comment]
Were the parameters of the three models averaged directly? 是不是直接三个模型参数平均得到的

**Comment by mZhenz** [comment]
+1, also curious
In my opinion, perhaps they just merge the response of the three model, like a multi-agent?

**Comment by HaoshengZou** [comment]
@zjuruizhechen @HqWei @mZhenz 
mergekit
```
models:
  - model: sft_model
  - model: dpo_model1
    parameters:
      density: 0.5
      weight: 0.6
  - model: dpo_model2
    parameters:
      density: 0.5
      weight: 0.5
merge_method: ties
base_model: sft_model
parameters:
  normalize: true
  int8_mask: true
dtype: bfloat16
```
https://huggingface.co/qihoo360/Light-R1-32B/discussions/1
